# .streamlit/secrets. toml

# Application security
APP_PASSWORD = "password"

# API Configuration 
GEMINI_API_KEY = "your.api-key.here"

# Additional security settings can be added here
ALLOWED_ATTEMPTS = 3
SESSION_TIMEOUT = 3600 # in seconds
